### ISSUE TITLE
Dataproc "apt-get update" failed on ubuntu20

### ISSUE THREAD

**Issue by viadea** [GoogleCloudDataproc/initialization-actions#1183]
On ubuntu 20 dataproc 2.1(At least this is what I have tested so far), the `apt-get update` failed with:
```
apt-get update
E: Repository 'https://packages.cloud.google.com/apt google-cloud-logging-focal-all InRelease' changed its 'Codename' value from 'google-cloud-logging-stretch-all' to 'google-cloud-logging-focal-all'
```
This caused our init script for dataproc fail as well. I believe it will impact many other init scripts for dataproc.
We can workaround it by :
```
apt-get  --allow-releaseinfo-change update
```

But this workaround has risks and I hope Google can fix this asap.

**Comment by FireByTrial** [comment]
same issue dataproc 2.0-debian10

**Comment by jayadeep-jayaraman** [comment]
This is being addressed [here] (https://github.com/GoogleCloudDataproc/initialization-actions/pull/1182)

**Comment by jayadeep-jayaraman** [comment]
Hi everyone there was an issue in our cloud logging agent because of which this issue has occured. This issue has been fixed as of May 16th and should be available in the Dataproc images next week.  

As a workaround please use an image version from Feb from anyone of the below list based on the version of interest
```
2.0.93-debian10, 2.0.93-rocky8, 2.0.93-ubuntu18
2.1.41-debian11, 2.1.41-rocky8, 2.1.41-ubuntu20, 2.1.41-ubuntu20-arm
2.2.7-debian12, 2.2.7-rocky9, 2.2.7-ubuntu22
```

if this is not a valid workaround then I would request you manually add `apt-get  --allow-releaseinfo-change update` to the init script for this week till the new image comes out next week.

**Comment by cjac** [comment]
This should be resolved now.
