### ISSUE TITLE
GPU not detected by yarn or spark

### ISSUE THREAD

**Issue by Arun-Krishna** [GoogleCloudDataproc/initialization-actions#888]
Hi,

I created a cluster with the gpu init-action using this command:

```bash
gcloud dataproc clusters create ${CLUSTER_NAME} \
    --region=us-central1 \
    --enable-component-gateway \
    --zone=us-central1-a \
    --master-machine-type n1-standard-2 \
    --worker-machine-type n1-standard-2 \
    --image-version=2.0-debian10 \
    --initialization-actions "gs://${INIT_PATH}/install_gpu_driver.sh" \
    --metadata gpu-driver-provider=NVIDIA \
    --worker-accelerator type=nvidia-tesla-p4 \
    --metadata install-gpu-agent=true \
    --scopes https://www.googleapis.com/auth/monitoring.write
```

No error when running `nvidia-smi` in the worker nodes, the GPUs are detected. But yarn and spark don't seem to be picking it up.

1.  when I check in the yarn resource manager, it is not detecting the gpu resources, only `<memory:52896, vCores:16>`. 
2. I copied the matrix computation example mentioned in [docs](https://cloud.google.com/dataproc/docs/concepts/compute/gpus#example_gpu_job) to a file `sparkJob.scala`, and ran this command:

   ```bash
   cat sparkJob.scala | spark-shell --conf spark.executor.resource.gpu.amount=1 --conf spark.task.resource.gpu.amount=0.5 --conf spark.executor.resource.gpu.discoveryScript=/usr/lib/spark/scripts/gpu/getGpusResources.sh
   ```

But I still didn't see any GPU related metrics getting published via the gpu agent in cloud monitoring.

Am I missing any config in any of these steps?

**Comment by bradmiro** [comment]
@mengdong can you please assist? I was working with @Arun-Krishna earlier on this, and grabbed this screenshot of the Yarn Resource Manager.
![screenshot](https://user-images.githubusercontent.com/22894295/111534022-e0405780-873d-11eb-8c2a-03859f0fce2e.png)

**Comment by mengdong** [comment]
Hi @bradmiro we have a getting started guide here.
https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-gcp.html

I think the issue is that you didn't specify meta tag: 
```
    --metadata gpu-driver-provider="NVIDIA" \
    --metadata rapids-runtime=SPARK \
```

I suggest we remove OS installed GPU driver and use NVIDIA provided driver as default going forward, and set both SPARK and Dask as default when deploy the init script. If @bradmiro and @medb agree, I can clean up those.

Thanks!

**Comment by Arun-Krishna** [comment]
Hi @mengdong, 
I added the meta tag `--metadata gpu-driver-provider=NVIDIA` in my create command, but not the rapids tag as I didn't include the rapids init-action. Is it not possible to use spark with GPU without rapids?
Also, shouldn't the GPU still get shown in the yarn resource manager?

**Comment by mengdong** [comment]
Hi @Arun-Krishna, without rapids, your SparkSQL won't be able to leverage GPU. 

In this case, I suggest we move https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/rapids/rapids.sh#L209-L217 to gpu init script.

The reason you don't see GPU in yarn is because of https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/rapids/rapids.sh#L209-L217

**Comment by Arun-Krishna** [comment]
Yes, GPU is getting detected in yarn after adding this restart step. Thanks!
