### ISSUE TITLE
GPU Debian initialization action broken

### ISSUE THREAD

**Issue by bradmiro** [GoogleCloudDataproc/initialization-actions#926]
Error installing GPU drivers on debian images:

```
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
```

@mengdong would you mind taking a look?

**Comment by mengdong** [comment]
Hi @bradmiro , by default, in RAPIDS, we don't install nccl. I guess the problem happens when you try to install NCCL, the fix should be changing the nccl version, change only the debian and ubuntu NCCL version to 2.8.3 (centos still 2.8.4), see https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/
